[project]
name = "kokoro-onnx"
version = "0.1.0"
description = "TTS with kokoro and onnx runtime"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnxruntime>=1.20.1",
    "phonemizer>=3.3.0",
    "soundfile>=0.13.0",
    'piper-phonemize-fork>=1.2.0 ; platform_system != "Linux"',
    'piper-phonemize-cross>=1.2.1 ; platform_system == "Linux"',
]
